youtube/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "posts#index"
   get 'posts/:id/download', to: 'posts#download', as: 'download_post'
   
end

youtube/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

youtube/app/models/post.rb
class Post < ApplicationRecord
    
    has_one_attached :image
    has_one_attached :video
end

youtube/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

youtube/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

youtube/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end
  
  def download
    @post = Post.find(params[:id])
    send_data @post.video.download, filename: @post.video.filename.to_s
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :descritpion, :image, :video)
    end
end

youtube/app/helpers/application_helper.rb
module ApplicationHelper
end

youtube/app/helpers/posts_helper.rb
module PostsHelper
end

youtube/app/views/layouts/_footer.html.erb
<!-- component -->
<!-- Foooter -->
<footer class="" style="background-color: #282828;    box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
  left: 0; bottom: 0; width: 100%; position: fixed;">
    
  <div class="max-w-screen-xl px-4 py-12 mx-auto space-y-8 overflow-hidden sm:px-6 lg:px-8"  >
    <nav class="flex flex-wrap justify-center -mx-5 -my-2">
      <div class="px-5 py-2">
        <a href="#" class="text-base leading-6 text-white hover:text-gray-200">
          About
        </a>
      </div>
      <div class="px-5 py-2">
        <a href="#" class="text-base leading-6 text-white hover:text-gray-200">
          Blog
        </a>
      </div>
      <%# if current_user %>
      <div class="px-5 py-2">
        <%#= link_to "Account details", edit_user_registration_path, class:"text-base leading-6 text-white hover:text-gray-200" %>
      </div>
      <%# end %>
    </nav>
    <p class="mt-8 text-base leading-6 text-center text-gray-400">
      © 2023 Crumble All rights reserved.
    </p>
  </div>
</footer>

youtube/app/views/layouts/_navbar.html.erb
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Poppins:wght@500&family=Roboto:wght@500&display=swap" rel="stylesheet">
<!-- component -->
<div class="flex-wrap place-items-center">
  <section class="relative mx-auto">
    <!-- navbar -->
    <nav class="flex justify-between text-white " style="background-color: #282828;    box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;">
      <div class="flex items-center w-full px-5 py-6 xl:px-12">
        <a class="text-3xl font-bold font-heading" href="/">
          <!-- <img class="h-9" src="logo.png" alt="logo"> -->
          Youtube
        </a>
        <!-- Nav Links -->
        <ul class="hidden px-4 mx-auto space-x-12 font-semibold md:flex font-heading">
          <li><a class="hover:text-gray-200" href="/">Home</a></li>
          <% if current_user %>
            <li><a class="hover:text-gray-200" href="#">  <%= link_to "Upload", new_post_path %></a></li>
            <li><a class="hover:text-gray-200" href="#">  <%#= link_to "My Media", pages_media_path %></a></li>
            <li>
              <a class="hover:text-gray-200">
                <%#= link_to "Profile", current_user %>
              </a></li>
            <%= button_to("Log Out",destroy_user_session_path, method: :delete) %></li>
          <% else %>
            <li><a class="hover:text-gray-200" href="#">  <%= link_to "Sign up", new_user_registration_path %></a></li>
        </ul>
      <% end %>
      <!-- Header Icons -->
    </div>
    <!-- Responsive navbar -->
    <%#= render "layouts/search_bar"%>
  </nav>
</section>
</div>

youtube/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Youtube</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

youtube/app/views/posts/_form.html.erb
<%= form_with(model: post, class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="px-3 py-2 mt-3 font-medium text-red-500 rounded-lg bg-red-50">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", rows: 5 %>
  </div>
  <div class="my-5">
    <%= form.label :video %>
    <%= form.file_field :video, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", accept: "video/*" %>
  </div>
  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <%#= form.hidden_field :user_id, value: current_user.id %>
  <div class="inline">
    <%= form.submit "Upload Video", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

youtube/app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="youtube-layout">
  <%# post.video.blob.metadata.fetch(:duration, nil) %>
  <% if post.image.attached? %>
    <%= image_tag(post.image, class: "thumbnail") %>
  <% end %>
  <% if action_name != "show" %>
    <%= link_to post, class: "overlay" do %>
      <div class="overlay-content">
        <h2 class="post-title"><%= post.title %></h2>
        <p class="text-white post-details">
          <%#= post.user.email %>
          <br>
          Posted <%= time_ago_in_words(post.created_at) %> ago
        </p>
      </div>
    <% end %>
  <% end %>
</div>
<style>
  .youtube-layout {
    position: relative;
    width: 24%;
    height: 200px;
    box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
    display: inline-block;
    align-items: center; /* Center vertically */
    justify-content: center; /* Center horizontally */
  }

  .thumbnail {
    display: block;
    max-width: 100%;
    max-height: 100%;
    width: 100%; /* Fill the container width */
    height: 100%; /* Fill the container height */
    object-fit: cover; /* Maintain aspect ratio and fill the container */
  }

  .overlay {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    color: white;
    background-color: rgba(0, 0, 0, 0.7);
    text-decoration: none;
    display: flex;
    align-items: center;
    justify-content: center;
    opacity: 0;
    transition: opacity 0.3s;
  }

  .overlay-content {
    text-align: center;
  }

  .overlay:hover {
    opacity: 1;
  }

  .overlay:hover .thumbnail {
    filter: brightness(70%);
  }

  .post-title {
    font-size: 18px;
    font-weight: bold;
    margin-bottom: 8px;
  }

  .post-details {
    font-size: 14px;
  }

  /* Responsive changes */
  @media screen and (max-width: 768px) {
    .youtube-layout {
      width: 100%;
    }
  }
</style>

youtube/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

youtube/app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>


<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>

  <% end %>
</div>

youtube/app/views/posts/new.html.erb
<div class="w-full mx-auto md:w-2/3">
  <%= render "form", post: @post %>
  <%#= link_to 'Back to posts', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

youtube/app/views/posts/show.html.erb
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<div class="youtube-layout">
  <% if @post.video.attached? %>
    <div class="video-container">
      <video controls>
        <source src="<%= url_for(@post.video) %>" type="video/mp4">
        Your browser does not support the video tag.
      </video>
    </div>
  <% else %>
    <% if @post.image.attached? %>
      <%= image_tag(@post.image, class: "thumbnail") %>
    <% end %>
  <% end %>
  <div class="overlay">
    <div class="overlay-content">
      <h2 class="text-lg post-details"><%= @post.title %></h2>
      <h2 class="text-lg post-details"><%#= @post.hits %> views </h2>
      <p class="post-details">
        <%#= @post.user.email %>
        <br>
        <%= time_ago_in_words(@post.created_at) %> ago
      </p>
    </div>
  </div>
  <% if current_user %>
    <div>
      <%#= button_to "like", likes_path, params: {like: {post_id: @post.id}}, method: :post, class:"mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%#= @post.likes.count %>
    </div>
    <%#if @post.user_id == current_user.id %>
      <%#= link_to 'Edit', edit_post_path(@post), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <div class="inline-block ml-2 ">
        <%#= button_to 'Delete', post_path(@post), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      </div>
    <%# end %>
  <% end %>
  <% if @post.video.attached? %>
    <%= link_to 'Download', download_post_path(@post), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
  <% end %>
</div>
<style>
  .youtube-layout {
  margin: 0 auto;
  width: 60%;
  box-shadow: rgba(0, 0, 0, 0.2) 0px 0px 8px 0px;
  }

  .thumbnail {
   display: block;
   max-width: 100%;
   max-height: 100%;
   width: auto;
   height: auto;
   margin: 0 auto;
   object-fit: contain;
  }

  .post-details {
  padding: 10px;
  }

  .post-title {
  font-size: 24px;
  font-weight: bold;
  margin-bottom: 8px;
  }

  .post-details p {
  font-size: 14px;
  }      .video-container {
        position: relative;
        padding-bottom: 56.25%; /* 16:9 aspect ratio (change as needed) */
        padding-top: 30px;
        height: 0;
        overflow: hidden;
      }

      .video-container video {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
      }
</style>